# Переменные окружения для кластера Kafka
x-connect: &kafka-common-env
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  # Настройка защищенного SSL-соединения
  KAFKA_SSL_KEYSTORE_TYPE: JKS
  KAFKA_SSL_TRUSTSTORE_TYPE: JKS
  KAFKA_SSL_TRUSTSTORE_PASSWORD: your-password
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"

  # Настройка SASL для аутентификации
  KAFKA_ZOOKEEPER_SASL_CLIENT: true
  KAFKA_ZOOKEEPER_SET_ACL: true
  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  KAFKA_LISTENERS: SASL_SSL://0.0.0.0:9092
  KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL
  KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
  KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
  KAFKA_SUPER_USERS: User:admin
  KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/config/kafka_server_jaas.conf"
  KAFKA_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="your-password";
  KAFKA_LISTENER_NAME_SASL_SSL_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="your-password" user_admin="your-password" user_kafka="your-password";

services:
  # Сервис ZooKeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper.sasl.jaas.conf:/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
      - ./kafka-0-creds:/etc/zookeeper/secrets
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
        -Dzookeeper.authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dzookeeper.allowSaslFailedClients=false
        -Dzookeeper.requireClientAuthScheme=sasl
    networks:
      kafka-connect-network:

  # Kafka-брокер 1/3
  kafka-0:
    container_name: kafka-0
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - ./kafka-0-creds:/etc/kafka/secrets
      - ./kafka_server_jaas.conf:/etc/kafka/config/kafka_server_jaas.conf
      - ./admin.properties:/etc/kafka/secrets/admin.properties
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 0
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-0:9092
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka-0.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-0_keystore_creds
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-0.truststore.jks
      KAFKA_SSL_KEY_CREDENTIALS: kafka-0_sslkey_creds
    networks:
      kafka-connect-network:

  # Kafka-брокер 2/3
  kafka-1:
    container_name: kafka-1
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
      - "9095:9095"
    volumes:
      - ./kafka-1-creds:/etc/kafka/secrets
      - ./kafka_server_jaas.conf:/etc/kafka/config/kafka_server_jaas.conf
      - ./admin.properties:/etc/kafka/secrets/admin.properties
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-1:9092
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka-1.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-1_keystore_creds
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-1.truststore.jks
      KAFKA_SSL_KEY_CREDENTIALS: kafka-1_sslkey_creds
    networks:
      kafka-connect-network:

  # Kafka-брокер 3/3
  kafka-2:
    container_name: kafka-2
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9096:9096"
      - "9097:9097"
    volumes:
      - ./kafka-2-creds:/etc/kafka/secrets
      - ./kafka_server_jaas.conf:/etc/kafka/config/kafka_server_jaas.conf
      - ./admin.properties:/etc/kafka/secrets/admin.properties
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 2
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-2:9092
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka-2.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-2_keystore_creds
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-2.truststore.jks
      KAFKA_SSL_KEY_CREDENTIALS: kafka-2_sslkey_creds
    networks:
      kafka-connect-network:

  app-producer:
    image: python:3.13
    container_name: app-producer
    volumes:
      - ./ca.crt:/app/ca.crt
      - ./producer.py:/app/producer.py
      - ./kafka-0-creds:/app/kafka-0-creds
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
      SASL_USERNAME: producer
      SASL_PASSWORD: your-password
    working_dir: /app
    command: sh -c "pip install --upgrade pip wheel setuptools confluent-kafka && python producer.py && tail -f /dev/null"
    networks:
      kafka-connect-network:

  app-consumer:
    image: python:3.13
    container_name: app-consumer
    volumes:
      - ./ca.crt:/app/ca.crt
      - ./consumer.py:/app/consumer.py
      - ./kafka-0-creds:/app/kafka-0-creds
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
      KAFKA_GROUP_ID: consumer-ssl-group
      SASL_USERNAME: consumer
      SASL_PASSWORD: your-password
    working_dir: /app
    command: sh -c "pip install --upgrade pip wheel setuptools confluent-kafka && python consumer.py && tail -f /dev/null"
    networks:
      kafka-connect-network:

networks:
  kafka-connect-network:
    name: kafka-connect-network
