-- Создание потока сообщений
CREATE STREAM MESSAGES_STREAM (
  USER_ID VARCHAR,
  RECIPIENT_ID VARCHAR,
  MESSAGE VARCHAR,
  TIMESTAMP BIGINT
) WITH (
  KAFKA_TOPIC='messages',
  VALUE_FORMAT='JSON'
  );

-- Таблица общего количества отправленных сообщений
CREATE TABLE TOTAL_MESSAGES_SENT AS
SELECT
  USER_ID,
  COUNT(*) AS MESSAGE_COUNT
FROM MESSAGES_STREAM
GROUP BY USER_ID
EMIT CHANGES;

-- Таблица для уникальных комбинаций (user_id, recipient_id)
CREATE TABLE UNIQUE_USER_RECIPIENT WITH (KEY_FORMAT='JSON') AS
SELECT
  USER_ID,
  RECIPIENT_ID,
  COUNT(*) AS OCCURRENCES
FROM MESSAGES_STREAM
GROUP BY USER_ID, RECIPIENT_ID
EMIT CHANGES;

-- Таблица подсчёта уникальных получателей
CREATE TABLE UNIQUE_RECIPIENTS AS
SELECT
  USER_ID,
  COUNT(*) AS UNIQUE_RECIPIENT_COUNT
FROM UNIQUE_USER_RECIPIENT
GROUP BY USER_ID
EMIT CHANGES;

-- Таблица с наиболее активными пользователями
CREATE TABLE TOP_ACTIVE_USERS AS
SELECT
  USER_ID,
  COUNT(*) AS SENT_MESSAGES
FROM MESSAGES_STREAM
GROUP BY USER_ID
EMIT CHANGES;

-- Таблица для общей статистики по каждому пользователю
CREATE TABLE USER_STATISTICS AS
SELECT
  T.USER_ID AS USER_ID,
  T.MESSAGE_COUNT AS TOTAL_MESSAGES,
  COALESCE(U.UNIQUE_RECIPIENT_COUNT, CAST(0 AS BIGINT)) AS UNIQUE_RECIPIENTS
FROM TOTAL_MESSAGES_SENT T
LEFT OUTER JOIN UNIQUE_RECIPIENTS U ON T.USER_ID = U.USER_ID
EMIT CHANGES;


